# Generated by Django 5.2 on 2025-05-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimbingan',
            name='status',
            field=models.CharField(choices=[('sedang diperiksa', 'Sedang Diperiksa'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='Sedang Diperiksa', max_length=50),
        ),
    ]
