# Generated by Django 5.2 on 2025-05-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bimbingan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimbingan',
            name='alasan_reject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
