# Generated by Django 5.2 on 2025-05-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bimbingan_alasan_reject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bimbingan',
            name='alasan_reject',
        ),
    ]
