# Generated by Django 5.2 on 2025-05-16 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_bimbingan_alasan_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='bukti_file',
            field=models.FileField(blank=True, null=True, upload_to='bukti_milestone/'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='is_approved',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='milestone',
            name='tanggal_disetujui',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='tanggal_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DeadlineChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_deadline', models.DateField()),
                ('new_deadline', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.milestone')),
            ],
        ),
    ]
